# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_to', models.CharField(help_text='comma separated emails', max_length=2048)),
                ('email_from', models.CharField(help_text='comma separated emails', max_length=2048)),
                ('email_subject', models.CharField(max_length=2048)),
                ('email_body', models.CharField(max_length=8000)),
                ('email_attachment', models.CharField(help_text='file attachment path', max_length=2000)),
                ('status', models.BooleanField(default=False, help_text='False: not sent, True: email sent')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='email insert date time')),
                ('modify_date', models.DateTimeField(auto_now=True, help_text='email sent date time')),
            ],
            options={
                'db_table': 'EmailOutbox',
            },
        ),
    ]
