# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=400)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('review_status', models.CharField(choices=[(b'OPEN', b'OPEN'), (b'REVIEWED', b'REVIEWED'), (b'PROCESSING', b'PROCESSING'), (b'RESOLVED', b'RESOLVED'), (b'CLOSED', b'CLOSED')], default='OPEN', max_length=100)),
                ('status', models.BooleanField(default=False, help_text='False: not sent, True: email sent')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='email insert date time')),
                ('modify_date', models.DateTimeField(auto_now=True, help_text='email sent date time')),
            ],
            options={
                'db_table': 'ContactRequest',
            },
        ),
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_to', models.CharField(help_text='comma separated emails', max_length=2048)),
                ('email_from', models.CharField(help_text='comma separated emails', max_length=2048)),
                ('email_subject', models.CharField(max_length=2048)),
                ('email_body', models.CharField(max_length=8000)),
                ('email_attachment', models.CharField(help_text='file attachment path', max_length=2000)),
                ('status', models.BooleanField(default=False, help_text='False: not sent, True: email sent')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='email insert date time')),
                ('modify_date', models.DateTimeField(auto_now=True, help_text='email sent date time')),
            ],
            options={
                'db_table': 'EmailOutbox',
            },
        ),
    ]
