# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 01:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='target object id , could be anything', max_length=100)),
                ('object_model', models.CharField(help_text='object model', max_length=100)),
                ('object_name', models.CharField(help_text='Item title or etc', max_length=200)),
                ('object_visitor', models.CharField(help_text='logged in user identifier', max_length=200)),
                ('object_visitor_type', models.CharField(help_text='logged in user type', max_length=200)),
                ('other_data', models.CharField(help_text='Other information related to the user or item, prefer to insert json data here', max_length=8000)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Analytics',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_photo', models.ImageField(null=True, upload_to='businesses/banner/%Y/%m/%d')),
                ('popularity_rating', models.IntegerField(default=0, help_text='Rating, max 10 min 0', null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('web_address', models.URLField(help_text='website url', null=True)),
                ('photo', models.ImageField(null=True, upload_to='businesses/%Y/%m/%d')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Listing start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Listing end time', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_min', models.IntegerField(help_text='min price', null=True)),
                ('price_max', models.IntegerField(help_text='max price', null=True)),
                ('video_url', models.URLField(blank=True)),
                ('exclusive', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Business',
            },
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[(b'Monday', b'Monday'), (b'Tuesday', b'Tuesday'), (b'Wednesday', b'Wednesday'), (b'Thursday', b'Thursday'), (b'Friday', b'Friday'), (b'Saturday', b'Saturday'), (b'Sunday', b'Sunday')], max_length=10)),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'BusinessHour',
            },
        ),
        migrations.CreateModel(
            name='BusinessPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='businesses/%Y/%m/%d')),
                ('tag', models.CharField(choices=[(b'H', b'Helpful'), (b'I', b'Inappropriate')], max_length=20, null=True)),
                ('photo_type', models.CharField(choices=[(b'BP', b'BusinessPhoto'), (b'RP', b'ReviewPhoto'), (b'UP', b'UserPhoto')], max_length=20, null=True)),
                ('caption', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
            options={
                'db_table': 'BusinessPhoto',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.FileField(blank=True, null=True, upload_to='categories/icon/')),
                ('slug', models.CharField(blank=True, max_length=500, null=True)),
                ('category_type', models.CharField(choices=[(b'E', b'Event'), (b'B', b'Business')], default=b'B', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Category')),
            ],
            options={
                'db_table': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Country code', max_length=10, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.FileField(blank=True, null=True, upload_to='avatars/%Y/%m/%d')),
                ('user_type', models.CharField(choices=[(b'C', b'Customer'), (b'B', b'Business'), (b'M', b'Moderator')], default=b'B', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('event_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('where', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='business.Category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Customer')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='EventDiscussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Event')),
            ],
            options={
                'db_table': 'EventDiscussion',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Feature',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_upload_type', models.CharField(choices=[(b'businesses/banner/%Y/%m/%d', b'BUSINESS_BANNER'), (b'businesses/%Y/%m/%d', b'BUSINESS_PHOTO'), (b'avatars/%Y/%m/%d', b'AVATARS'), (b'news/%Y/%m/%d', b'NEWS'), (b'event/%Y/%m/%d', b'EVENT')], default=b'businesses/banner/%Y/%m/%d', max_length=200)),
                ('file_path', models.FileField(upload_to=b'')),
            ],
            options={
                'db_table': 'FileUpload',
            },
        ),
        migrations.CreateModel(
            name='ListingFaq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ListingFaq',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('photo', models.ImageField(null=True, upload_to='news/%Y/%m/%d')),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'NewsCategory',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='review_attachment')),
                ('rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=500)),
                ('review', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Customer')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=20)),
                ('tag', models.CharField(choices=[(b'LOVE', b'LOVE'), (b'INTERESTING', b'INTERESTING'), (b'LOL', b'LOL')], max_length=20)),
                ('key', models.CharField(max_length=32, null=True)),
                ('cookie', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Review')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ReviewTag',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.NewsCategory'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Country'),
        ),
        migrations.AddField(
            model_name='businessphoto',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Review'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_hours',
            field=models.ManyToManyField(to='business.BusinessHour'),
        ),
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(to='business.Category'),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.City'),
        ),
        migrations.AddField(
            model_name='business',
            name='faq',
            field=models.ManyToManyField(blank=True, to='business.ListingFaq'),
        ),
        migrations.AddField(
            model_name='business',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Add features', to='business.Feature'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Customer'),
        ),
    ]
