# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Customer')),
            ],
            options={
                'db_table': 'BusinessBookmark',
            },
        ),
    ]
