# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 01:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_upload_type', models.CharField(choices=[(b'businesses/banner/%Y/%m/%d', b'BUSINESS_BANNER'), (b'businesses/%Y/%m/%d', b'BUSINESS_PHOTO'), (b'avatars/%Y/%m/%d', b'AVATARS'), (b'news/%Y/%m/%d', b'NEWS'), (b'event/%Y/%m/%d', b'EVENT')], default=b'businesses/banner/%Y/%m/%d', max_length=200)),
                ('file_path', models.FileField(upload_to=b'')),
            ],
            options={
                'db_table': 'FileUpload',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='business',
            name='country',
        ),
        migrations.RemoveField(
            model_name='business',
            name='price_range',
        ),
        migrations.AddField(
            model_name='business',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='price_max',
            field=models.IntegerField(help_text='max price', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='price_min',
            field=models.IntegerField(help_text='min price', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='categories/icon/'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.City'),
        ),
        migrations.AlterField(
            model_name='business',
            name='end_time',
            field=models.TimeField(help_text='Listing end time', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='features',
            field=models.ManyToManyField(help_text='Add features', null=True, to='business.Feature'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='popularity_rating',
            field=models.IntegerField(default=0, help_text='Rating, max 10 min 0', null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='start_time',
            field=models.TimeField(help_text='Listing start time', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='web_address',
            field=models.URLField(help_text='website url', null=True),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='closing_hours',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='day',
            field=models.CharField(choices=[(b'Monday', b'Monday'), (b'Tuesday', b'Tuesday'), (b'Wednesday', b'Wednesday'), (b'Thursday', b'Thursday'), (b'Friday', b'Friday'), (b'Saturday', b'Saturday'), (b'Sunday', b'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='opening_hours',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[(b'E', b'Event'), (b'B', b'Business')], default=b'B', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='Country code', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Country'),
        ),
    ]
