# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=1024)),
                ('message', models.CharField(max_length=8000)),
                ('read_by', models.CharField(default=False, help_text='Boolean field to indicate if the contact request is read by someone or not, 0-> unread, 1-> read', max_length=500)),
                ('reader_comments', models.CharField(help_text='Comments by reader of this contact request', max_length=4000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ContactUsRequest',
            },
        ),
    ]
